### ISSUE TITLE
Set up a publicly available DDNS (dynamic domain name server) to host the backend REST API

### ISSUE THREAD

**Issue by richardbinder** [bluedodecahedron/tsrapp#3]
[No-IP](https://www.noip.com/) will be used to provide a fixed internet URL for the backend REST API.

**Comment by bluedodecahedron** [comment]
When started, the REST API server is now available at [http://trafficsignapp.ddns.net](http://trafficsignapp.ddns.net). It uses the standard port 80 for http web servers.
